""" Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. """

def fibonacci(lenth):
    z = 0   
    x = 0
    y = 1
    arr = []
    total = 0
    while z < lenth:
        z = x + y
        x = y
        y = z
        arr.append(z) 
    
    for i in arr:
        if i % 2 == 0:
            total += i

    return total

print(fibonacci(4000000))